# Generated by Django 2.2.2 on 2019-07-25 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_auto_20190724_1444'),
        ('billing', '0003_balance_logtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='LogTransaction',
        ),
    ]
