# Generated by Django 2.2.2 on 2019-07-25 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190724_1444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_auto_20190725_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionsLog',
            new_name='TransactionsLogs',
        ),
    ]
