# Generated by Django 2.2.2 on 2019-07-25 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_auto_20190724_1444'),
        ('billing', '0005_auto_20190725_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionsLogs',
            new_name='TransactionsLog',
        ),
    ]
