# Generated by Django 2.2.2 on 2019-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20190725_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionslog',
            name='balance',
        ),
        migrations.AddField(
            model_name='transactionslog',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionslog',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionslog',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
