# Generated by Django 2.2.2 on 2019-07-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20190726_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionslog',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactionslog',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactionslog',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
