# Generated by Django 2.2.2 on 2019-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('1', 'customer'), ('2', 'executor')], max_length=20),
        ),
    ]
