# Generated by Django 2.2.2 on 2019-07-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190724_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogTransaction',
        ),
    ]
